apiVersion: v1
kind: Service
metadata:
  name: zts-cmc-app-svc
  labels:
    app: zts-cmc-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: zts-cmc-app
