apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: zts-cmc
  namespace: default 
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - zts-cmc-app
