apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: zts-cmc-app-subscription
  namespace: default
  labels:
    app: zts-cmc-app
  annotations:
    apps.open-cluster-management.io/github-path: cmcui
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: default/zts-cmc-gitops
  placement:
    placementRef:
      name: zts-cmc-app-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
